import fs from "fs";

let jsonText = fs.readFileSync(`result.json`, "utf-8");
let map = new Map(JSON.parse(jsonText));
map.forEach((val, key) => {
    if (!fs.existsSync(`latest/${key}`)) {
        fs.mkdirSync(`latest/${key}`);
        let val = map.get(key);
        fs.writeFileSync(
            `latest/${key}/index.html`,
            `<!DOCTYPE html><html lang="en"><head> <meta charset="utf-8"> <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no"> <title>Listen to ${key}</title> <link rel="stylesheet" href="/assets/bootstrap/css/bootstrap.min.css"> <link rel="stylesheet" href="/assets/css/Montserrat.css"> <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/baguettebox.js/1.11.1/baguetteBox.min.css"> <link rel="stylesheet" href="/assets/css/vanilla-zoom.min.css"> <link rel="icon" href="/assets/img/favicon.ico"></head><body><nav class="navbar navbar-light navbar-expand-lg fixed-top bg-white clean-navbar"> <div class="container"><a class="navbar-brand logo" href="#">ListenTo</a> <button data-bs-toggle="collapse" class="navbar-toggler" data-bs-target="#navcol-1"><span class="visually-hidden">Toggle navigation</span><span class="navbar-toggler-icon"></span></button> <div class="collapse navbar-collapse" id="navcol-1"> <ul class="navbar-nav ms-auto"> <li class="nav-item"><a class="nav-link" href="../..">Home</a></li><li class="nav-item"><a class="nav-link" href="..">Latest</a></li><li class="nav-item"><a class="nav-link" href="../../about">About</a></li></ul> </div></div></nav><main class="page product-page"> <section class="clean-block clean-product dark"> <div class="container"> <div class="block-heading"><h2 class="text-info">${key}</h2> <p>from ListenTo 📡</p></div><div class="block-content"> <div class="product-info"> <div class="row"> <div class="col-md-6"> <div id="product-preview" class="vanilla-zoom"> <div class="zoomed-image"><img src="http://47.113.231.184/${key}/image.jpeg" class="zoomed-image"/></div><div class="sidebar"></div></div></div><div class="col-md-6"> <div class="info"><h3>${key}</h3> <div class="price"> <audio src="http://47.113.231.184/${key}/audio.m4a" controls></audio> </div><div class="summary"><p>${val}</p></div></div></div></div></div></div></div></section></main><footer class="page-footer dark"> <div class="footer-copyright"> <p>Copyleft <svg xmlns="http://www.w3.org/2000/svg" width="1rem" height="1rem" viewBox="0 0 980 980"> <circle cx="490" cy="490" r="440" fill="none" stroke="#fff" stroke-width="100"/> <path d="M219,428H350a150,150 0 1 1 0,125H219a275,275 0 1 0 0-125z" fill="#fff"/> </svg> 2022 Guanyun (Guy) Lu </p></div></footer><script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/baguettebox.js/1.11.1/baguetteBox.min.js"></script><script src="assets/js/vanilla-zoom.js"></script><script src="assets/js/theme.js"></script></body></html>`
        );
    }
});
fs.writeFileSync('latest/index.html', '<!DOCTYPE html><html lang="en"><head> <meta charset="utf-8"> <meta content="width=device-width, initial-scale=1.0, shrink-to-fit=no" name="viewport"> <title>ListenTo Latest</title> <link href="/assets/bootstrap/css/bootstrap.min.css" rel="stylesheet"> <link href="/assets/css/Montserrat.css" rel="stylesheet"> <link href="https://cdnjs.cloudflare.com/ajax/libs/baguettebox.js/1.11.1/baguetteBox.min.css" rel="stylesheet"> <link href="/assets/css/vanilla-zoom.min.css" rel="stylesheet"> <link href="assets/img/favicon.ico" rel="icon"></head><body><nav class="navbar navbar-light navbar-expand-lg fixed-top bg-white clean-navbar"> <div class="container"><a class="navbar-brand logo" href="#">ListenTo</a> <button class="navbar-toggler" data-bs-target="#navcol-1" data-bs-toggle="collapse"><span class="visually-hidden">Toggle navigation</span><span class="navbar-toggler-icon"></span></button> <div class="collapse navbar-collapse" id="navcol-1"> <ul class="navbar-nav ms-auto"> <li class="nav-item"><a class="nav-link" href="..">Home</a></li><li class="nav-item"><a class="nav-link active" href=".">Latest</a></li><li class="nav-item"><a class="nav-link" href="../about">About</a></li></ul> </div></div></nav><main class="page gallery-page"> <section class="clean-block clean-gallery dark"> <div class="container"> <div class="block-heading"> <h2 class="text-info">Latest</h2> <p>from ListenTo 📡</p></div>');
let cnt = 0;
map.forEach((val, key) => {
    if (cnt === 3) {
        cnt = 0;
        fs.appendFileSync('latest/index.html', '</div>');
    }
    if (cnt === 0)
        fs.appendFileSync('latest/index.html', '<div class="row">');
    fs.appendFileSync('latest/index.html', `<div class="col-md-6 col-lg-4 item"><a class="lightbox" href="${key}"><img class="img-thumbnail img-fluid image" src="http://47.113.231.184/${key}/image.jpeg"></a></div>`);
    cnt += 1;
})
fs.appendFileSync('latest/index.html', '</div></div></section></main><footer class="page-footer dark"> <div class="footer-copyright"> <p>Copyleft <svg xmlns="http://www.w3.org/2000/svg" width="1rem" height="1rem" viewBox="0 0 980 980"> <circle cx="490" cy="490" r="440" fill="none" stroke="#fff" stroke-width="100"/> <path d="M219,428H350a150,150 0 1 1 0,125H219a275,275 0 1 0 0-125z" fill="#fff"/> </svg> 2022 Guanyun (Guy) Lu </p></div></footer><script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/baguettebox.js/1.11.1/baguetteBox.min.js"></script><script src="assets/js/vanilla-zoom.js"></script><script src="assets/js/theme.js"></script></body></html>');